### ISSUE TITLE
How to make future predictions

### ISSUE THREAD

**Issue by dhsusf** [IKKIM00/stock_and_pm2.5_predicion_using_TFT#1]
Hi, first off, thank you for creating the notebooks. Really helpful.

I'm very new to machine learning models, self studying only for the last six months and way too old to go back to school to learn it. But I was wondering, how does one actually use the carrier notebook to make  future predictions. If i'm not mistaken, then the notebook currently is just training, testing, and validating on past dates and forecasts don't actually go into unseen future dates.

For example, today is 2022/1/25, how can I make a forecast for the next 1-5 days.

Thanks.

**Comment by IKKIM00** [comment]
Hi! 
Please refer to [TFT original paper](https://arxiv.org/abs/1912.09363)
Thanks!
